### ISSUE TITLE
Problems when back view is visible and user rotates

### ISSUE THREAD

**Issue by diversmi** [ipup/PPRevealSideViewController#111]
On iPhone...
with the following options:
    [_revealController resetOption:PPRevealSideOptionsiOS7StatusBarFading];
    [_revealController setOption:PPRevealSideOptionsiOS7StatusBarMoving];
When the back VC is revealed and the user rotates, the nav bar (right VC) slides up under the status bar.
The attachments show before rotation (portrait) and after rotation (landscape).
![screenshot 2014-08-05 10 55 35](https://cloud.githubusercontent.com/assets/7386113/3813863/9d9fefc4-1cb6-11e4-8261-e9caa6540e03.png)
![screenshot 2014-08-05 10 55 10](https://cloud.githubusercontent.com/assets/7386113/3813865/a8c629ea-1cb6-11e4-8f67-7a44bc0975b1.png)

Second problem, with the default options, the auto-added image under the status bar isn't wide enough after rotation, as shown in the following attachment.
![screen shot 2014-08-05 at 11 02 21 am](https://cloud.githubusercontent.com/assets/7386113/3813232/9c924960-1cb1-11e4-9314-768744707848.png)

**Comment by ipodishima** [comment]
Well yeah, you're right I'm not handling it :/

**Comment by ipodishima** [comment]
The moving aspect is a little bit too tricky for me to maintain, especially because I do not use it at all

**Comment by kakashysen** [comment]
Hi I updated the last release version 1.2.1 but I have the same problem, the status bar is black in the documentation say than I should "simple subclass PPReveal ..." https://github.com/ipup/PPRevealSideViewController#status-bar-style--hidden but I don't know how make that, somebody can help me please?
