### ISSUE TITLE
about  the PPRevealSideViewController  question

### ISSUE THREAD

**Issue by zeqinjie** [ipup/PPRevealSideViewController#112]
useing the PPRevealSideViewController when i not to  preloadViewController ,i found it would show a little excursion and report the error-[PPRevealSideViewController gestureRecognizerDidPan:] [Line 1129] ****** No controller to push ****** Think to preload controller ! ****** but i dont want to  preloadViewController in the right side,how to reslove

**Comment by ipodishima** [comment]
You do not have to do something about this. This is just a warning for you
