### ISSUE TITLE
can't hide status bar in side view controller

### ISSUE THREAD

**Issue by PadrePedro** [ipup/PPRevealSideViewController#114]
I cannot hide the status bar on the side view controller to hide (note white status bar at top).

![image](https://cloud.githubusercontent.com/assets/5768502/4339979/712f105a-4029-11e4-87ae-013d829897e8.png)

I've tried calling:
    [[UIApplication sharedApplication] setStatusBarHidden:YES withAnimation:NO];

Setting this:
- (BOOL)prefersStatusBarHidden
{
    return YES;
}

Am I doing something wrong?  Thanks.

**Comment by ipodishima** [comment]
I don't see how you can do this, except using the option to slide the status bar along with the center controller. But this is a trick I introduced (status bar screenshot)
