### ISSUE TITLE
blank status bar when pulling down

### ISSUE THREAD

**Issue by wangbourne** [ipup/PPRevealSideViewController#115]
see attached
![bug](https://cloud.githubusercontent.com/assets/2090084/4428485/c94cfa7e-45cc-11e4-9e26-7e243e8d2869.png)

**Comment by ipodishima** [comment]
Yes,

To be honest this is something related to the status bar handling on iOS side which I probably do not handle correctly or Apple is not letting us enough liberty to do so.
