### ISSUE TITLE
Preload ViewController blank while pan gesture is in progress

### ISSUE THREAD

**Issue by hermanccw** [ipup/PPRevealSideViewController#116]
Hi there,

I've preloaded a view controller for pan gesture in my main content view like this:

```
[self.revealSideViewController preloadViewController:self.leftMenuController forSide:PPRevealSideDirectionLeft];
```

however, when I try to drag from my content view controller, my "leftMenuController" does not come into screen until I release the drag.

any ideas?

**Comment by ipodishima** [comment]
That might be related on how you are dealing with the subviews building. Please provide any context

**Comment by VrasidasP** [comment]
I have the same problem. 
I'm preloading a left menu with - (void)preloadViewController:(UIViewController *)controller forSide:(PPRevealSideDirection)direction withOffset:(CGFloat)offset;

The menu is a normal UIViewController, and everything is fine.

But, when I'm adding the same UIViewController inside a UINavigationController and preload the navigation controller instead, the view only appears when I lift my finger from the opening pan gesture.

Any ideas?
