### ISSUE TITLE
can not set fakeiOS7StatusBarColor

### ISSUE THREAD

**Issue by disburden** [ipup/PPRevealSideViewController#117]
self.revealSideViewController.fakeiOS7StatusBarColor=[UIColor orangeColor];
    [self.revealSideViewController resetOption:PPRevealSideOptionsiOS7StatusBarFading];

Error:
[PPRevealSideViewController setFakeiOS7StatusBarColor:]: unrecognized selector sent to instance

**Comment by ipodishima** [comment]
No issue with mine. Maybe upgrade your version
