### ISSUE TITLE
How to initialize PPRevealSideViewController in a storyboard?

### ISSUE THREAD

**Issue by bagusflyer** [ipup/PPRevealSideViewController#21]
This component looks great. But there is only one issue for me to add it to my ios 5 project. My question is：

How to initialize PPRevealSideViewController in a storyboard? （Which will be root viewcontroller)

Any suggestion? Thanks

**Comment by victorynaveen** [comment]
Hi ,xaxa06 !!!,

Can you please send me the sample code which you  integrated pprevealsideview controller with storyboard.  Please its very urgent for me..
