### ISSUE TITLE
iOS6 Status Bar Color

### ISSUE THREAD

**Issue by Dwarf8** [ipup/PPRevealSideViewController#51]
In my app, the UINavigationBar tintColor is Purple, and status bar adopt this color.

I preloadViewController:menu forSide:PPRevealSideDirectionLeft and, when I tried to  popViewControllerWithNewCenterController,  the status bar color changes to black, insted of adopt the UINavigationBar color.

Any ideas?

Thxs!

**Comment by ipodishima** [comment]
This might help

```
- (UIViewController *)childViewControllerForStatusBarStyle 
{
    return self.topViewController;
}
```
