### ISSUE TITLE
Hello , Two Event Fire at a time when using this lib and sample code

### ISSUE THREAD

**Issue by tikamchandrakar18** [ipup/PPRevealSideViewController#92]
Using your sample code
Step to Reproduce
 Desc: In main cent
![photo 1](https://f.cloud.github.com/assets/1075877/2040501/98efa1d2-89b7-11e3-8518-a367068f433e.PNG)
er screen there have a lots of Option : Left, right, Switch Central , Nav ..... etc

When user click Left and Nav button on same time , then both the button are taking action , Means Display the Sliding screen and also the Push new screen.

Please look at the screen shot for More Detail,  same thing is happening in my App.  Please help me how to handle this?

**Comment by ipodishima** [comment]
Probably using one of the piece of code to disable the center view while opened
